### ISSUE TITLE
Flicking on nbbatman title screen and uccops first level 

### ISSUE THREAD

**Issue by wickerwaka** [MiSTer-devel/Arcade-IremM92_MiSTer#2]
Either the HINT timing is wrong or the latching of tile scroll offsets timing is wrong. Need to confirm on hardware.

**Comment by wickerwaka** [comment]
Fixed by 7b506c2ea5f93667d1251a3a14c83dc3b6d49e59

**Comment by wwark** [comment]
For information, the flickering on title screen of "Yakyuu Kakutou League-Man (Japan)" still present on japanese version of the game nbbatman.
